export const aboutMeMdPath = './md/about-me.md'
export const experienceMdPath = './md/experience.md'
export const projectsMdPath = './md/projects.md'
export const educationMdPath = './md/education.md'
export const skillsMdPath = './md/skills.md'
export const creditsMdPath = './md/credits.md'
